# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\addaccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(596, 518)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxAddaccountsOS = QtWidgets.QComboBox(Dialog)
        self.comboBoxAddaccountsOS.setObjectName("comboBoxAddaccountsOS")
        self.comboBoxAddaccountsOS.addItem("")
        self.comboBoxAddaccountsOS.addItem("")
        self.comboBoxAddaccountsOS.addItem("")
        self.comboBoxAddaccountsOS.addItem("")
        self.gridLayout.addWidget(self.comboBoxAddaccountsOS, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEditAddEmail = QtWidgets.QLineEdit(Dialog)
        self.lineEditAddEmail.setObjectName("lineEditAddEmail")
        self.gridLayout.addWidget(self.lineEditAddEmail, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 2, 1, 1)
        self.lineEditAddAccountProfileId = QtWidgets.QLineEdit(Dialog)
        self.lineEditAddAccountProfileId.setObjectName("lineEditAddAccountProfileId")
        self.gridLayout.addWidget(self.lineEditAddAccountProfileId, 1, 1, 1, 1)
        self.plainTextEditAddBulkAccounts = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEditAddBulkAccounts.setObjectName("plainTextEditAddBulkAccounts")
        self.gridLayout.addWidget(self.plainTextEditAddBulkAccounts, 5, 0, 1, 5)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.comboBoxAddType = QtWidgets.QComboBox(Dialog)
        self.comboBoxAddType.setObjectName("comboBoxAddType")
        self.comboBoxAddType.addItem("")
        self.comboBoxAddType.addItem("")
        self.comboBoxAddType.addItem("")
        self.gridLayout.addWidget(self.comboBoxAddType, 0, 1, 1, 1)
        self.comboBoxAddAccountDevices = QtWidgets.QComboBox(Dialog)
        self.comboBoxAddAccountDevices.setObjectName("comboBoxAddAccountDevices")
        self.comboBoxAddAccountDevices.addItem("")
        self.comboBoxAddAccountDevices.addItem("")
        self.comboBoxAddAccountDevices.addItem("")
        self.gridLayout.addWidget(self.comboBoxAddAccountDevices, 0, 3, 1, 1)
        self.lineEditAddNameProfile = QtWidgets.QLineEdit(Dialog)
        self.lineEditAddNameProfile.setObjectName("lineEditAddNameProfile")
        self.gridLayout.addWidget(self.lineEditAddNameProfile, 1, 3, 1, 2)
        self.lineEditAddPassword = QtWidgets.QLineEdit(Dialog)
        self.lineEditAddPassword.setObjectName("lineEditAddPassword")
        self.gridLayout.addWidget(self.lineEditAddPassword, 4, 3, 1, 2)
        self.pushButtoncancel = QtWidgets.QPushButton(Dialog)
        self.pushButtoncancel.setObjectName("pushButtoncancel")
        self.gridLayout.addWidget(self.pushButtoncancel, 6, 0, 1, 1)
        self.pushButtonAddaccount = QtWidgets.QPushButton(Dialog)
        self.pushButtonAddaccount.setObjectName("pushButtonAddaccount")
        self.gridLayout.addWidget(self.pushButtonAddaccount, 6, 1, 1, 4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBoxAddaccountsOS.setItemText(0, _translate("Dialog", "Window"))
        self.comboBoxAddaccountsOS.setItemText(1, _translate("Dialog", "Mac OS X"))
        self.comboBoxAddaccountsOS.setItemText(2, _translate("Dialog", "Linux"))
        self.comboBoxAddaccountsOS.setItemText(3, _translate("Dialog", "Chrome OS"))
        self.label_6.setText(_translate("Dialog", "Profile OS"))
        self.label_4.setText(_translate("Dialog", "Type"))
        self.label_5.setText(_translate("Dialog", "Profile Id"))
        self.label_3.setText(_translate("Dialog", "Name Profile"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.label.setText(_translate("Dialog", "Email"))
        self.comboBoxAddType.setItemText(0, _translate("Dialog", "Amazon"))
        self.comboBoxAddType.setItemText(1, _translate("Dialog", "Ebay"))
        self.comboBoxAddType.setItemText(2, _translate("Dialog", "Etzy"))
        self.comboBoxAddAccountDevices.setItemText(0, _translate("Dialog", "Desktop"))
        self.comboBoxAddAccountDevices.setItemText(1, _translate("Dialog", "iPhone"))
        self.comboBoxAddAccountDevices.setItemText(2, _translate("Dialog", "Android"))
        self.pushButtoncancel.setText(_translate("Dialog", "Cancel"))
        self.pushButtonAddaccount.setText(_translate("Dialog", "Add account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
