# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\addemails.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAddEmails(object):
    def setupUi(self, DialogAddEmails):
        DialogAddEmails.setObjectName("DialogAddEmails")
        DialogAddEmails.resize(610, 380)
        self.gridLayout = QtWidgets.QGridLayout(DialogAddEmails)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEditAddEmails = QtWidgets.QPlainTextEdit(DialogAddEmails)
        self.plainTextEditAddEmails.setObjectName("plainTextEditAddEmails")
        self.gridLayout.addWidget(self.plainTextEditAddEmails, 0, 0, 1, 2)
        self.pushButtonAddEmailCancel = QtWidgets.QPushButton(DialogAddEmails)
        self.pushButtonAddEmailCancel.setObjectName("pushButtonAddEmailCancel")
        self.gridLayout.addWidget(self.pushButtonAddEmailCancel, 1, 0, 1, 1)
        self.pushButtonAddEmails = QtWidgets.QPushButton(DialogAddEmails)
        self.pushButtonAddEmails.setObjectName("pushButtonAddEmails")
        self.gridLayout.addWidget(self.pushButtonAddEmails, 1, 1, 1, 1)

        self.retranslateUi(DialogAddEmails)
        QtCore.QMetaObject.connectSlotsByName(DialogAddEmails)

    def retranslateUi(self, DialogAddEmails):
        _translate = QtCore.QCoreApplication.translate
        DialogAddEmails.setWindowTitle(_translate("DialogAddEmails", "Dialog"))
        self.pushButtonAddEmailCancel.setText(_translate("DialogAddEmails", "Cancel"))
        self.pushButtonAddEmails.setText(_translate("DialogAddEmails", "Add emails"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAddEmails = QtWidgets.QDialog()
    ui = Ui_DialogAddEmails()
    ui.setupUi(DialogAddEmails)
    DialogAddEmails.show()
    sys.exit(app.exec_())
