# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\EmailSignupList.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogEmailSignupList(object):
    def setupUi(self, DialogEmailSignupList):
        DialogEmailSignupList.setObjectName("DialogEmailSignupList")
        DialogEmailSignupList.resize(1005, 521)
        self.gridLayout = QtWidgets.QGridLayout(DialogEmailSignupList)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetEmailSignupList = QtWidgets.QTableWidget(DialogEmailSignupList)
        self.tableWidgetEmailSignupList.setObjectName("tableWidgetEmailSignupList")
        self.tableWidgetEmailSignupList.setColumnCount(4)
        self.tableWidgetEmailSignupList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmailSignupList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmailSignupList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmailSignupList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmailSignupList.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidgetEmailSignupList, 1, 0, 1, 5)
        self.lineEditEmailSignupListFind = QtWidgets.QLineEdit(DialogEmailSignupList)
        self.lineEditEmailSignupListFind.setObjectName("lineEditEmailSignupListFind")
        self.gridLayout.addWidget(self.lineEditEmailSignupListFind, 0, 0, 1, 4)
        self.pushButtonEmailSignupListFind = QtWidgets.QPushButton(DialogEmailSignupList)
        self.pushButtonEmailSignupListFind.setObjectName("pushButtonEmailSignupListFind")
        self.gridLayout.addWidget(self.pushButtonEmailSignupListFind, 0, 4, 1, 1)
        self.comboBoxEmailSignupListType = QtWidgets.QComboBox(DialogEmailSignupList)
        self.comboBoxEmailSignupListType.setObjectName("comboBoxEmailSignupListType")
        self.comboBoxEmailSignupListType.addItem("")
        self.comboBoxEmailSignupListType.addItem("")
        self.gridLayout.addWidget(self.comboBoxEmailSignupListType, 2, 0, 1, 1)
        self.pushButtonEmailSignupListSpecificList = QtWidgets.QPushButton(DialogEmailSignupList)
        self.pushButtonEmailSignupListSpecificList.setObjectName("pushButtonEmailSignupListSpecificList")
        self.gridLayout.addWidget(self.pushButtonEmailSignupListSpecificList, 2, 3, 1, 2)
        self.pushButtonEmailSignupListBlackList = QtWidgets.QPushButton(DialogEmailSignupList)
        self.pushButtonEmailSignupListBlackList.setObjectName("pushButtonEmailSignupListBlackList")
        self.gridLayout.addWidget(self.pushButtonEmailSignupListBlackList, 2, 2, 1, 1)
        self.pushButtonEmailSignupListRefresh = QtWidgets.QPushButton(DialogEmailSignupList)
        self.pushButtonEmailSignupListRefresh.setObjectName("pushButtonEmailSignupListRefresh")
        self.gridLayout.addWidget(self.pushButtonEmailSignupListRefresh, 2, 1, 1, 1)

        self.retranslateUi(DialogEmailSignupList)
        QtCore.QMetaObject.connectSlotsByName(DialogEmailSignupList)

    def retranslateUi(self, DialogEmailSignupList):
        _translate = QtCore.QCoreApplication.translate
        DialogEmailSignupList.setWindowTitle(_translate("DialogEmailSignupList", "Dialog"))
        item = self.tableWidgetEmailSignupList.horizontalHeaderItem(0)
        item.setText(_translate("DialogEmailSignupList", "Email"))
        item = self.tableWidgetEmailSignupList.horizontalHeaderItem(1)
        item.setText(_translate("DialogEmailSignupList", "Password"))
        item = self.tableWidgetEmailSignupList.horizontalHeaderItem(2)
        item.setText(_translate("DialogEmailSignupList", "Note"))
        item = self.tableWidgetEmailSignupList.horizontalHeaderItem(3)
        item.setText(_translate("DialogEmailSignupList", "Created date"))
        self.pushButtonEmailSignupListFind.setText(_translate("DialogEmailSignupList", "Find"))
        self.comboBoxEmailSignupListType.setItemText(0, _translate("DialogEmailSignupList", "Hotmail"))
        self.comboBoxEmailSignupListType.setItemText(1, _translate("DialogEmailSignupList", "Amazon"))
        self.pushButtonEmailSignupListSpecificList.setText(_translate("DialogEmailSignupList", "Create specific list"))
        self.pushButtonEmailSignupListBlackList.setText(_translate("DialogEmailSignupList", "Create black list "))
        self.pushButtonEmailSignupListRefresh.setText(_translate("DialogEmailSignupList", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogEmailSignupList = QtWidgets.QDialog()
    ui = Ui_DialogEmailSignupList()
    ui.setupUi(DialogEmailSignupList)
    DialogEmailSignupList.show()
    sys.exit(app.exec_())
