# -*- mode: python ; coding: utf-8 -*-
# Spec file tối ưu kích thước: loại bỏ các Qt module không sử dụng

a = Analysis(
    ['MunAutomationDesktop\\main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('MunAutomationDesktop/style.qss', '.'),
        ('MunAutomationDesktop/icon.png', '.'),
        ('MunAutomationDesktop/mun_anti_browser/inject_scripts', 'mun_anti_browser/inject_scripts'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Loại bỏ các thư viện Qt không cần thiết để giảm kích thước exe
    excludes=[
        # Qt modules không dùng
        'PyQt6.Qt3DAnimation',
        'PyQt6.Qt3DCore',
        'PyQt6.Qt3DExtras',
        'PyQt6.Qt3DInput',
        'PyQt6.Qt3DLogic',
        'PyQt6.Qt3DRender',
        'PyQt6.QtBluetooth',
        'PyQt6.QtCharts',
        'PyQt6.QtDataVisualization',
        'PyQt6.QtDesigner',
        'PyQt6.QtHelp',
        'PyQt6.QtLocation',
        'PyQt6.QtMultimedia',
        'PyQt6.QtMultimediaWidgets',
        'PyQt6.QtNfc',
        'PyQt6.QtOpenGL',
        'PyQt6.QtOpenGLWidgets',
        'PyQt6.QtPdf',
        'PyQt6.QtPdfWidgets',
        'PyQt6.QtPositioning',
        'PyQt6.QtQml',
        'PyQt6.QtQuick',
        'PyQt6.QtQuick3D',
        'PyQt6.QtQuickWidgets',
        'PyQt6.QtRemoteObjects',
        'PyQt6.QtSensors',
        'PyQt6.QtSerialBus',
        'PyQt6.QtSerialPort',
        'PyQt6.QtSql',
        'PyQt6.QtSvg',
        'PyQt6.QtSvgWidgets',
        'PyQt6.QtTest',
        'PyQt6.QtTextToSpeech',
        'PyQt6.QtVirtualKeyboard',
        # Thư viện Python không dùng
        'tkinter',
        'unittest',
        'xmlrpc',
        'pydoc',
        'doctest',
        'difflib',
        'calendar',
        'email',
        'html',
        'http.server',
        'lib2to3',
        'multiprocessing',
        'test',
        'distutils',
        'setuptools',
        'pkg_resources',
        'xml',
        'xmlrpc',
        'ftplib',
        'telnetlib',
        'turtle',
        'curses',
    ],
    noarchive=False,
    optimize=1,  # Tối ưu bytecode Python (loại bỏ assert và docstring)
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='C69Automation',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='MunAutomationDesktop/icon.ico',
)
