# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\profileaddaccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 316)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.pushButtonProfileAddAccountcancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonProfileAddAccountcancel.setObjectName("pushButtonProfileAddAccountcancel")
        self.gridLayout.addWidget(self.pushButtonProfileAddAccountcancel, 5, 0, 1, 1)
        self.lineEditProfileAddAccountPassword = QtWidgets.QLineEdit(Dialog)
        self.lineEditProfileAddAccountPassword.setObjectName("lineEditProfileAddAccountPassword")
        self.gridLayout.addWidget(self.lineEditProfileAddAccountPassword, 3, 3, 1, 2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.lineEditProfileAddAccountEmail = QtWidgets.QLineEdit(Dialog)
        self.lineEditProfileAddAccountEmail.setObjectName("lineEditProfileAddAccountEmail")
        self.gridLayout.addWidget(self.lineEditProfileAddAccountEmail, 3, 1, 1, 1)
        self.comboBoxProfileAddAccountType = QtWidgets.QComboBox(Dialog)
        self.comboBoxProfileAddAccountType.setObjectName("comboBoxProfileAddAccountType")
        self.comboBoxProfileAddAccountType.addItem("")
        self.comboBoxProfileAddAccountType.addItem("")
        self.comboBoxProfileAddAccountType.addItem("")
        self.gridLayout.addWidget(self.comboBoxProfileAddAccountType, 0, 1, 1, 4)
        self.lineEditProfileAddAccountID = QtWidgets.QLineEdit(Dialog)
        self.lineEditProfileAddAccountID.setObjectName("lineEditProfileAddAccountID")
        self.gridLayout.addWidget(self.lineEditProfileAddAccountID, 1, 1, 1, 4)
        self.pushButtonProfileAddaccount = QtWidgets.QPushButton(Dialog)
        self.pushButtonProfileAddaccount.setObjectName("pushButtonProfileAddaccount")
        self.gridLayout.addWidget(self.pushButtonProfileAddaccount, 5, 1, 1, 4)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.plainTextEditProfileAddAccountNote = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEditProfileAddAccountNote.setObjectName("plainTextEditProfileAddAccountNote")
        self.gridLayout.addWidget(self.plainTextEditProfileAddAccountNote, 4, 0, 1, 5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Type"))
        self.pushButtonProfileAddAccountcancel.setText(_translate("Dialog", "Cancel"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.label.setText(_translate("Dialog", "Email"))
        self.comboBoxProfileAddAccountType.setItemText(0, _translate("Dialog", "Amazon"))
        self.comboBoxProfileAddAccountType.setItemText(1, _translate("Dialog", "Ebay"))
        self.comboBoxProfileAddAccountType.setItemText(2, _translate("Dialog", "Etzy"))
        self.pushButtonProfileAddaccount.setText(_translate("Dialog", "Add account"))
        self.label_3.setText(_translate("Dialog", "Profile ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
