# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sshsetup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialogssh(object):
    def setupUi(self, Dialogssh):
        Dialogssh.setObjectName("Dialogssh")
        Dialogssh.resize(734, 584)
        self.gridLayout = QtWidgets.QGridLayout(Dialogssh)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialogssh)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEditsshfailed = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEditsshfailed.setObjectName("plainTextEditsshfailed")
        self.gridLayout_2.addWidget(self.plainTextEditsshfailed, 1, 0, 1, 1)
        self.plainTextEditssh = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEditssh.setObjectName("plainTextEditssh")
        self.gridLayout_2.addWidget(self.plainTextEditssh, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 2, 7)
        self.btncancelssh = QtWidgets.QPushButton(Dialogssh)
        self.btncancelssh.setObjectName("btncancelssh")
        self.gridLayout.addWidget(self.btncancelssh, 3, 6, 1, 1)
        self.btnokssh = QtWidgets.QPushButton(Dialogssh)
        self.btnokssh.setObjectName("btnokssh")
        self.gridLayout.addWidget(self.btnokssh, 3, 4, 1, 2)
        self.cbsshdatabase = QtWidgets.QComboBox(Dialogssh)
        self.cbsshdatabase.setEditable(True)
        self.cbsshdatabase.setObjectName("cbsshdatabase")
        self.gridLayout.addWidget(self.cbsshdatabase, 0, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(Dialogssh)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.btnimporttextssh = QtWidgets.QPushButton(Dialogssh)
        self.btnimporttextssh.setObjectName("btnimporttextssh")
        self.gridLayout.addWidget(self.btnimporttextssh, 0, 5, 1, 2)
        self.lineEditimporttext = QtWidgets.QLineEdit(Dialogssh)
        self.lineEditimporttext.setObjectName("lineEditimporttext")
        self.gridLayout.addWidget(self.lineEditimporttext, 0, 3, 1, 2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialogssh)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(5, 59, 2, 2))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.retranslateUi(Dialogssh)
        QtCore.QMetaObject.connectSlotsByName(Dialogssh)

    def retranslateUi(self, Dialogssh):
        _translate = QtCore.QCoreApplication.translate
        Dialogssh.setWindowTitle(_translate("Dialogssh", "Dialog"))
        self.groupBox.setTitle(_translate("Dialogssh", "add ssh"))
        self.btncancelssh.setText(_translate("Dialogssh", "Cancel"))
        self.btnokssh.setText(_translate("Dialogssh", "Ok"))
        self.label_5.setText(_translate("Dialogssh", "ssh catalogue"))
        self.btnimporttextssh.setText(_translate("Dialogssh", "File"))
